# Generated by Django 4.2.7 on 2024-03-20 10:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="user",
            name="qr_code",
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("4fac9008-7490-4fff-b91a-56fa3936397e"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
