# Generated by Django 4.2.7 on 2024-03-20 10:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_user_created_at_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("0fb64a39-b480-443e-8ac4-553116b20a55"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
