# Generated by Django 4.2.7 on 2024-03-20 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_alter_user_options_alter_user_id_alter_user_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("538b0309-e24d-4bbc-a6ff-7d1913b2d42e"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
