# Generated by Django 4.2.7 on 2024-03-20 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("f04739ac-aa5f-40e8-a829-82275240a859"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
