# Generated by Django 4.2.7 on 2024-03-20 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0010_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("19173d8a-31b5-42b9-94a7-4bb65f88e01c"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
