# Generated by Django 4.2.7 on 2024-03-20 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0011_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("51b5fb95-4cc3-49f3-84d5-ecb0b2e91515"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
