# Generated by Django 4.2.7 on 2024-03-20 11:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0012_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("31f8c549-c5c8-4461-82f7-3da52151cde8"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
