# Generated by Django 4.2.7 on 2024-03-21 09:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0013_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="priority_locations",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("534f3fba-1179-4123-b3c0-bf3f32c59e5d"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
